<a href="https://colab.research.google.com/github/sowji281/githubTest/blob/main/pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 print("hello")

hello


## pytorch_fundamentals
resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/


import torch
import numpy as  np
import pandas as pd 
print(torch.__version__)

In [2]:
import torch
import numpy as  np
import pandas as pd 
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## introduction to tensors

### creating tensor 
pytorch tensors are created using torch.tensor() :https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()


7

In [7]:
#vector 
vector  =torch.tensor([2,5])
vector 

tensor([2, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
matrix= torch.tensor([[7,8],
                      [10,5]])
matrix

tensor([[ 7,  8],
        [10,  5]])

In [11]:
matrix.ndim


2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
#tensor
tensor= torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor.ndim

3

In [17]:
tensor[0,1,2]

tensor(6)

### random tensors
random tensors ar every important because the way many neural networks learn is that start with the random numbers and then adjust those random numbers to better represent the data 


In [18]:
# create a random  tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.1811, 0.3581, 0.1475, 0.8597],
        [0.0960, 0.7930, 0.8405, 0.0505],
        [0.6158, 0.2668, 0.9416, 0.2529]])

In [19]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[5.8038e-01, 9.7725e-01, 8.7660e-01, 4.9922e-01, 9.9007e-02,
          5.7671e-01, 2.9972e-01, 8.5323e-01, 9.1776e-02, 7.6902e-01],
         [6.8405e-01, 7.6813e-01, 9.6703e-01, 5.9378e-01, 1.2959e-01,
          5.9393e-01, 6.5496e-01, 6.8840e-01, 9.7509e-01, 7.2985e-01],
         [8.3794e-01, 4.5137e-01, 3.3651e-01, 5.3423e-01, 4.5598e-01,
          5.6302e-01, 9.5172e-01, 9.3119e-01, 7.8295e-01, 5.1139e-01],
         [4.3527e-01, 2.4747e-01, 7.7824e-02, 1.4687e-01, 5.3184e-01,
          8.1014e-01, 9.9878e-01, 4.9132e-01, 3.3107e-01, 6.0773e-01],
         [8.3533e-01, 1.9600e-01, 6.5018e-02, 5.3043e-01, 6.6215e-01,
          5.9512e-01, 3.3223e-01, 7.4228e-02, 5.3052e-01, 3.5651e-01],
         [6.8768e-01, 3.0275e-01, 8.2487e-04, 4.6556e-01, 8.5119e-01,
          9.0491e-01, 9.3318e-01, 9.4180e-01, 7.4495e-01, 8.2844e-01],
         [2.6014e-01, 4.0947e-01, 8.8129e-01, 9.8551e-01, 3.7689e-01,
          7.6926e-02, 1.9333e-01, 9.9338e-01, 1.8299e-01, 9.0785e-02],
         [1.8

In [20]:
random_tensor.ndim

3

In [21]:
# create a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width,color
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
torch.rand(3,3)

tensor([[0.2558, 0.2587, 0.2896],
        [0.2225, 0.7684, 0.5413],
        [0.1855, 0.5997, 0.8215]])

In [23]:
### create all zeros and ones 
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
zeros= torch.zeros(3,4)
zeros



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### create a range of tensors and tensors -like


In [25]:
#use  torch.arange() and get deprecated message,use torch.arange()
one_to_ten=torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
torch.__version__

'1.13.1+cu116'

In [27]:
#crzeate tensors like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:

#tensor data types
float_32_tensor  = torch.tensor([3.0,6.0,7.0],
                                dtype=None, # what datatype is the  tensor 
                                device=None, # what device is your tensor on 
                                requires_grad=False) # whether or not to track gradients  with operations 
float_32_tensor 
 

tensor([3., 6., 7.])

In [31]:
float_32_tensor.dtype

torch.float32